name: Bump Migration Number

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push a new tag
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - 'config/*.json'  

jobs:
  bumpMigration:    
    name: Bump Migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done    

      - name: Rename file
        run: |      
          mv "data-sync-1.js" "data-sync-2.js"  

      - name: Commit fix
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: rename
          file_pattern: "data-sync-*.js" 
          