name: RBAC Data Migration

on:
  merge_group:
    types: [checks_requested]
      
concurrency: db-migration-prd     
      
jobs:
  # Confirmation step - prd
  confirm-db-migration-prd:
    name: Confirm db migration in prd
    runs-on: [ubuntu-latest]
    environment: db-migration-prd
    steps:
      - name: Confirm deployment
        run: |
          echo "Production DB migration confirmed"      
