name: List file changes 2

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/migrations/data/roles.json"
      - "src/migrations/data/permissions.json"
      - "src/migrations/data/service-accounts.json"
      - "src/migrations/data/global-policies.json"
      - "src/migrations/rbac-data-sync-*.js"

jobs:
  list_changes:
    name: List file changes
    runs-on: [ubuntu-latest]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: read # needed for PR event trigger

    steps:
      - uses: actions/checkout@v3
      - name: Filter migration data files
        id: migration_files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/migrations/data/roles.json
            src/migrations/data/permissions.json
            src/migrations/data/service-accounts.json
            src/migrations/data/global-policies.json
            src/migrations/rbac-data-sync-*.js

      - name: Run a step if rbac-data-sync-*.js was renamed
        id: check_rbac_data_renamed
        if: |
           (contains(steps.migration_files.outputs.renamed_files, 'rbac-data-sync')
           || (contains(steps.migration_files.outputs.deleted_files, 'rbac-data-sync') &&
              contains(steps.migration_files.outputs.added_files, 'rbac-data-sync')))
        run: |
          echo "renamed=true" >> $GITHUB_OUTPUT
          echo "rbac-data-sync file has not been renamed."
    
      - name: Run a step if migration data files was changed
        id: check_migration_data_changed
        if: steps.migration_files.outputs.any_changed == 'true'
        run: |
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Migration data files changed"
          
      - name: Run a step if rbac-data-sync-*.js was modified
        id: check_rbac_data_modified 
        if: |
          (steps.check_rbac_data_renamed.outputs.renamed != 'true' && contains(steps.migration_files.outputs.modified_files, 'rbac-data-sync'))
        run: |
          echo "modified=true" >> $GITHUB_OUTPUT
          echo "rbac-data-sync file has been modified."    
  
      - name: Check outputs
        run: |
          echo "steps.check_rbac_data_renamed.outputs.renamed: ${{steps.check_rbac_data_renamed.outputs.renamed}}"
          echo "steps.check_migration_data_changed.outputs.changed: ${{steps.check_migration_data_changed.outputs.changed}}"
          echo "steps.check_rbac_data_modified.outputs.modified: ${{steps.check_rbac_data_modified.outputs.modified}}"

#       - name: Bumping migration number
#         if: |
#           (steps.check_rbac_data_renamed.outputs.renamed != 'true' && steps.check_migration_data_changed.outputs.changed == 'true')
#         working-directory: ./src/migrations/
#         run: |
#          echo "Bumping migration number"
#          mv rbac-data-sync-*.js rbac-data-sync-$(($(echo rbac-data-sync-*.js | grep -oE '[0-9]+')+1)).js

#       - name: Commit renamed migration file
#         if: |
#           (steps.check_rbac_data_renamed.outputs.renamed != 'true' && steps.check_migration_data_changed.outputs.changed == 'true')
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#            commit_message: bump migration number on rbac-data-sync file
#            file_pattern: "src/migrations/rbac-data-sync-*.js"
           
