name: List file changes 2

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/migrations/data/roles.json"
      - "src/migrations/data/permissions.json"
      - "src/migrations/data/service-accounts.json"
      - "src/migrations/data/global-policies.json"
      - "src/migrations/rbac-data-sync-*.js"

jobs:
  list_changes:
    name: List file changes
    runs-on: [ubuntu-latest]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: read # needed for PR event trigger

    steps:
      - uses: actions/checkout@v3
      - name: Filter migration data files
        id: migration_files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/migrations/data/roles.json
            src/migrations/data/permissions.json
            src/migrations/data/service-accounts.json
            src/migrations/data/global-policies.json
            src/migrations/rbac-data-sync-*.js

      - name: Run a step if rbac-data-sync-*.js was renamed
        if: contains(steps.migration_files.outputs.renamed_files, 'rbac-data-sync')
        run: |
          echo "rbac_data_sync_renamed=true" >> $GITHUB_ENV
          echo "rbac-data-sync file has been renamed."
          
      - name: Run a step if migration data files was changed
        if: env.rbac_data_sync_renamed != true && steps.migration_files.outputs.any_changed == 'true'
        run: |
          echo "data_changed=true" >> $GITHUB_ENV
          echo "Migration data files changed"
          
      - name: Run a step if rbac-data-sync-*.js was modified
        if: env.rbac_data_sync_renamed != true && contains(steps.migration_files.outputs.modified_files, 'rbac-data-sync')
        run: |
          echo "rbac_data_sync_modified=true" >> $GITHUB_ENV
          echo "rbac-data-sync file has been modified."    
          
      - name: Bumping migration number
        working-directory: ./src/migrations/
        run: |
         echo "Bumping migration number"
         mv rbac-data-sync-*.js rbac-data-sync-$(($(echo rbac-data-sync-*.js | grep -oE '[0-9]+')+1)).js

      - name: Commit renamed migration file
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: bump migration number on rbac-data-sync file
           file_pattern: "src/migrations/rbac-data-sync-*.js"
           
