name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          
      - name: Validate JSON
        uses: cardinalby/schema-validator-action@v2
        with:
          file: 'config/roles.json'
          schema: 'config/schema/roles-schema.json'
